[tasks.linux_core]
  deps = ["coreinstall", "zsh", "python", "r2", "pwntools"]
  links = [
    [".config/terminator/config", "linux/core/.config/terminator/config"],
    [".SpaceVim.d/autoload/main.vim", "linux/core/.SpaceVim.d/autoload/main.vim"],
    [".SpaceVim.d/init.toml", "linux/core/.SpaceVim.d/init.toml"],
    [".radare2rc", "linux/core/.radare2rc"],
  ]

[tasks.linux_vm]
  deps = ["linux_core"]
  links = [
    [".zshrc", "linux/vm/.zshrc"]
  ]

[tasks.linux_com]
  deps = ["linux_core"]
  links = [
    [".zshrc", "linux/com/.zshrc"]
  ]

#install stuff

[macros.install]
  prefix = ["sudo", "apt-get", "install", "-y"]

[macros.pip]
  prefix = ["pip", "install", "--user"]

[macros.gem]
  prefix = ["sudo", "gem", "install"]

[macros.shell]
  prefix = ["sh", "-c"]

[macros.clone]
  deps = ["git"]
  prefix = ["git", "clone"]

[tasks.git]
  rejects = [["which", "git"]]
  cmds = [
    ["@install", "git"]
  ]

[tasks.zsh]
  cmdspre = [
    ["@install", "zsh"],
    #["@shell", "chsh -s `which zsh`"],
    ["@shell", "curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | zsh"],
    ["@clone", "https://github.com/bhilburn/powerlevel9k.git", ".oh-my-zsh/custom/themes/powerlevel9k"],
    ["@clone", "https://github.com/zsh-users/zsh-completions.git", ".oh-my-zsh/custom/plugins/zsh-completions"],
    ["@clone", "https://github.com/zsh-users/zsh-syntax-highlighting.git", ".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"],
    ["@clone", "https://github.com/zsh-users/zsh-autosuggestions.git", ".oh-my-zsh/custom/plugins/zsh-autosuggestions"],
  ]
  cmdspost = [
    ["@install", "terminator"],
  ]

[tasks.coreinstall]
  cmdspre = [
    ["@shell", "curl -sLf https://spacevim.org/install.sh | bash"],
    ["@shell", "curl -fsSL https://get.docker.com | bash"],
    ["git", "config", "credential.helper", "store"]
  ]
  cmds = [
    ["@install", "build-essential", "libssl-dev", "libffi-dev"],
    ["@install", "vim", "make", "gcc", "cmake", "wget", "neofetch", "ruby-full", "neovim"],
    ["sudo", "dpkg", "--add-architecture", "i386"],
    ["sudo", "apt", "update"],
    ["@install", "multiarch-support"],
    ["@install", "libc6:i386", "libncurses5:i386", "libstdc++6:i386"]
  ]

[tasks.python]
  cmds = [
    ["@install", "python", "python-dev", "python-pip"],
    ["@install", "python3", "python3-dev", "python3-pip"],
  ]

[tasks.r2]
  cmds = [
    ["@clone", "https://github.com/radare/radare2.git", ".radare2"],
    [".radare2/sys/install.sh"]
  ]

[tasks.pwntools]
  cmds = [
    ["@gem", "one_gadget", "seccomp-tools"],
    ["@pip", "capstone", "pwntools"],
    ["@install", "libc6-dbg", "gdb", "valgrind"]
  ]
