## Overarching Tasks

[tasks.linux_ns]
  deps = ["linux_common", "fish"]
  cmdspre = [
    ["@clone", "https://github.com/jimeh/tmux-themepack", ".tmux-themepack"]
  ]
  links = [
    [".config/fish/", "linux/ns/.config/fish/"],
    [".config/nvim/", "linux/ns/.config/nvim/"],
    [".tmux.conf", "linux/ns/.tmux.conf"]
  ]

[tasks.linux_common]
  deps = ["common", "tmux", "neovim"]
  cmds = [
    ["@install", "binutils", "build-essential", "cmake", "make", "gcc"],
    ["@install", "python", "python3", "python-dev", "python3-dev", "python-pip", "python3-pip"],
    ["@install", "vim", "wget", "neofetch", "ruby-full"],
  ]

## Individual Tasks

[tasks.common]
  links = [
    [".gitconfig", "common/.gitconfig"]
  ]

[tasks.fish]
  cmds = [
    ["@install", "fish"],
  ]

[tasks.tmux]
  cmds = [
    ["@install", "tmux"],
  ]

[tasks.neovim]
	deps = ["appimage"]
  cmds = [
    ["curl", "-LO", "https://github.com/neovim/neovim/releases/download/stable/nvim.appimage"],
    ["chmod", "u+x", "nvim.appimage"],
    ["mv", "./nvim.appimage", "/usr/bin/nvim"],

    ["curl", "-fLo", "~/.local/share/nvim/site/autoload/plug.vim", "--create-dirs", "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"],
    ["nvim", "+PluginInstall", "+qall"]
  ]

[tasks.r2]
  cmds = [
    ["@clone", "https://github.com/radare/radare2.git", ".radare2"],
    [".radare2/sys/install.sh"]
  ]

[tasks.pwntools]
  cmds = [
    ["sudo", "dpkg", "--add-architecture", "i386"],
    ["sudo", "apt", "update"],
    ["@install", "multiarch-support"],
    ["@install", "libc6:i386", "libncurses5:i386", "libstdc++6:i386"],

    ["@gem", "one_gadget", "seccomp-tools"],
    ["@pip", "capstone", "pwntools"],
    ["@install", "libc6-dbg", "gdb", "valgrind"]
  ]

[tasks.node]
  cmds = [
    ["@shell", "curl -o- https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash"],
  ]
  cmdspost = [
    ["nvm", "install", "--lts"],
    ["@npm", "live-server", "tldr"]
  ]

[tasks.appimage]
  cmds = [
		["@install", "fuse", "module-init-tools"],
		["sudo", "modprobe", "fuse"],
		["sudo", "groupadd", "fuse"],
		["@shell", "sudo useradd -a -G fuse $(whoami)"],
	]


## Macros

[macros.install]
  prefix = ["sudo", "apt-get", "install", "-y"]

[macros.pip]
  prefix = ["pip", "install", "--user"]

[macros.npm]
  prefix = ["npm", "i", "-g"]

[macros.gem]
  prefix = ["sudo", "gem", "install"]

[macros.shell]
  prefix = ["sh", "-c"]

[macros.clone]
  deps = ["git"]
  prefix = ["git", "clone"]

[tasks.git]
  rejects = [["which", "git"]]
  cmds = [
    ["@install", "git"]
  ]
